name = "JUtils"
uuid = "b878f980-060b-4e94-a3f0-02a5d9bcb82b"
authors = ["gpucce <g.puccetti92@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Animations = "27a7e980-b3e6-11e9-2bcd-0b925532e340"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Javis = "78b212ba-a7f9-42d4-b726-60726080707e"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ROCAnalysis = "f535d66d-59bb-5153-8d2b-ef0a426c6aff"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ROCAnalysis = "0.3"
julia = "1.6.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
