name = "JUtils"
uuid = "4f042127-57a9-4bde-85e4-f51c8b0fbe3c"
authors = ["gpucce <g.puccetti92@gmail.com>"]
version = "0.1.0"

[deps]
Animations = "27a7e980-b3e6-11e9-2bcd-0b925532e340"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Javis = "78b212ba-a7f9-42d4-b726-60726080707e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
